### ISSUE TITLE
add sphinx github action

### ISSUE THREAD

**Issue by cjkrolak** [cjkrolak/ThermostatSupervisor#855]
automate sphinx API doc updates with GitHub action:

.github/workflows/sphinx.yml

```
name: Sphinx Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx

      - name: Build documentation
        run: |
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
```
