### ISSUE TITLE
install docker scout CLI into ADO action

### ISSUE THREAD

**Issue by cjkrolak** [cjkrolak/ThermostatSupervisor#877]
https://github.com/docker/scout-cli

add to ADO pipeline after docker build:

```
    - task: CmdLine@2
      displayName: Find CVEs on image
      inputs:
        script: |
          # Install the Docker Scout CLI
          curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s --
          # Login to Docker Hub required for Docker Scout CLI
          docker login -u $(DOCKER_HUB_USER) -p $(DOCKER_HUB_PAT)
          # Get a CVE report for the built image and fail the pipeline when critical or high CVEs are detected
          docker scout cves $(image):$(tag) --exit-code --only-severity critical,high
```
