### ISSUE TITLE
Add AzureDevOps code coverage summary

### ISSUE THREAD

**Issue by cjkrolak** [cjkrolak/ThermostatSupervisor#879]
https://stackoverflow.com/questions/68452774/azure-devops-pipeline-showing-code-coverage-report-for-python-project

```
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10'
    - script: python -m pip install --upgrade pip setuptools
      displayName: Upgrade pip and setuptools
    - script: python -m pip install -r requirements.txt
      displayName: Install all dependencies
    - script: pre-commit run --all-files
      displayName: Check code quality
    - script: |
        coverage run -m pytest
        coverage xml -o coverage.xml
      displayName: Generate coverage report
    - task: PublishCodeCoverageResults@2
      inputs:
        summaryFileLocation: '**/coverage.xml'
```
