### ISSUE TITLE
add github token to ado script to avoid download limit

### ISSUE THREAD

**Issue by cjkrolak** [cjkrolak/ThermostatSupervisor#884]
```
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
    addSpnToEnvironment: true
  displayName: 'Use Python $(python.version)'
  env:
    GITHUB_TOKEN: $(GITHUB_TOKEN)
```
